name: Lint

on:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry>=1.0.0
        poetry config virtualenvs.create false
        poetry install
    - name: Lint with black
      run: |
        poetry run black --check c4p2n
    - name: Check types with mypy
      run: |
        poetry run mypy c4p2n
